spring:
  security:
    oauth2:
      client:
        registration:
          github:
            clientId: Ov23liOzlaAkxe2nNd85
            clientSecret: ca5012c337ff22f879ac5b1db1422aa83817fbeb
  application:
    name: NetflixMovies

  data:
    mongodb:
      host: localhost
      port: 27017
      database: NetflixMovies